# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  hardware.firmware = [ pkgs.linux-firmware ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3ac0f3dc-710b-498f-beae-1ce808ff4dcb";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF28-1E23";
    fsType = "vfat";
    options = [
      "fmask=0133"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/swapfile"; }
  ];
}
