{
  lib,
  callPackage,
  linuxPackagesFor,
  _kernelPatches ? [ ],
}@args:

let
  extraArgs = lib.removeAttrs args [
    "lib"
    "callPackage"
    "linuxPackagesFor"
    "_kernelPatches"
  ];

  linux-asahi-pkg =
    {
      stdenv,
      lib,
      fetchFromGitHub,
      buildLinux,
      ...
    }:
    buildLinux (
      lib.recursiveUpdate rec {
        inherit stdenv lib;

        pname = "linux-asahi";
        version = "7.1.13";
        modDirVersion = version;
        extraMeta.branch = "7.0";

        src = fetchFromGitHub {
          owner = "AsahiLinux";
          repo = "linux";
          tag = "asahi-${version}-3";
          hash = "sha256-quvdcQ2LbYQyCDQFKc6KPjWv+f5fpWfUrXo5Id0kpwE=";
        };

        ignoreConfigErrors = true;

        kernelPatches = [
          {
            name = "Asahi config";
            patch = null;
            structuredExtraConfig = with lib.kernel; {
              # Needed for GPU
              ARM64_16K_PAGES = yes;

              ARM64_MEMORY_MODEL_CONTROL = yes;
              ARM64_ACTLR_STATE = yes;

              # Might lead to the machine rebooting if not loaded soon enough
              APPLE_WATCHDOG = yes;

              # Can not be built as a module, defaults to no
              APPLE_M1_CPU_PMU = yes;

              # Defaults to 'y', but we want to allow the user to set options in modprobe.d
              HID_APPLE = module;

              APPLE_PMGR_MISC = yes;
              APPLE_PMGR_PWRSTATE = yes;

              NVME_HOST_AUTH = lib.mkForce no;

              # Disable irrelevant entries.
              DRM_AMDGPU = no;
              DRM_NOUVEAU = no;
              DRM_RADEON = no;

              WLAN_VENDOR_ATH = no;
              WLAN_VENDOR_INTEL = no;
              WLAN_VENDOR_MEDIATEK = no;

              NET_VENDOR_AMD = no;
              NET_VENDOR_INTEL = no;
              NET_VENDOR_NVIDIA = no;

              # Unused virtualization
XEN = lib.mkForce no;
HYPERV = lib.mkForce no;

# Wrong Broadcom Wi-Fi implementations
B43 = no;
B43LEGACY = no;
BRCMSMAC = no;

# Completely irrelevant buses/features
FSL_MC_BUS = no;
WAN = lib.mkForce no;
SPEAKUP = no;

# Legacy framebuffer hardware
FB_NVIDIA = no;
FB_RIVA = no;
FB_I740 = no;
FB_RADEON = no;
FB_ATY128 = no;
FB_ATY = no;
FB_SAVAGE = no;
FB_SIS = no;
FB_NEOMAGIC = no;
FB_KYRO = no;
FB_3DFX = no;
FB_VOODOO1 = no;
FB_TRIDENT = no;
FB_PM2 = no;
FB_PM3 = no;
FB_CIRRUS = no;
FB_IMX = no;
FB_CYBER2000 = no;
FB_UVESA = no;
FB_OPENCORES = no;
FB_XILINX = no;
FB_TFT = no;

ARCH_SUNXI = no;
ARCH_BCM = no;
ARCH_HISI = no;
ARCH_MEDIATEK = no;
ARCH_NXP = no;
ARCH_QCOM = no;
ARCH_TEGRA = no;

RDS = no;
TIPC = no;
ATM = no;
PHONET = no;
IEEE802154 = no;
#QRTR = no;
CAN = no;
NFC = no;
#WWAN = no;

# Unused filesystems.
XFS_FS = no;
OCFS2_FS = no;
BTRFS_FS = no;
F2FS_FS = lib.mkForce no;
VBOXSF_FS = no;
CEPH_FS = no;

APPLE_MAILBOX = yes;
APPLE_RTKIT = yes;
RUST_APPLE_RTKIT = yes;

ATA = no;
SCSI_LOWLEVEL = lib.mkForce no;
SCSI = yes;
NVME_FABRICS = no;
NVME_TARGET = lib.mkForce no;
MAC80211 = no;
DVB_CORE = no;

NVME_RDMA = no;
NVME_FC = no;
NVME_TCP = no;

# No built-in Ethernet controller.
NET_VENDOR_3COM = no;
NET_VENDOR_ACTIONS = no;
NET_VENDOR_ADAPTEC = no;
NET_VENDOR_AGERE = no;
NET_VENDOR_ALACRITECH = no;
NET_VENDOR_AMAZON = no;
NET_VENDOR_AQUANTIA = no;
NET_VENDOR_ARC = no;
NET_VENDOR_ASIX = no;
NET_VENDOR_ATHEROS = no;
NET_VENDOR_BROADCOM = no;
NET_VENDOR_CADENCE = no;
NET_VENDOR_CAVIUM = no;
NET_VENDOR_CHELSIO = no;
NET_VENDOR_CISCO = no;
NET_VENDOR_CORTINA = no;
NET_VENDOR_DAVICOM = no;
NET_VENDOR_DEC = no;
NET_VENDOR_DLINK = no;
NET_VENDOR_EMULEX = no;
NET_VENDOR_ENGLEDER = no;
NET_VENDOR_EZCHIP = no;
NET_VENDOR_FUNGIBLE = no;
NET_VENDOR_GOOGLE = no;
NET_VENDOR_HISILICON = no;
NET_VENDOR_HUAWEI = no;
NET_VENDOR_ADI = no;
NET_VENDOR_LITEX = no;
NET_VENDOR_MARVELL = no;
NET_VENDOR_MEDIATEK = lib.mkForce no;
NET_VENDOR_MELLANOX = no;
NET_VENDOR_META = no;
NET_VENDOR_MICREL = no;
NET_VENDOR_MICROCHIP = no;
NET_VENDOR_MICROSEMI = no;
NET_VENDOR_MICROSOFT = no;
NET_VENDOR_MUCSE = no;
NET_VENDOR_MYRI = no;
NET_VENDOR_NI = no;
NET_VENDOR_NATSEMI = no;
NET_VENDOR_NETRONOME = no;
NET_VENDOR_8390 = no;
NET_VENDOR_OKI = no;
NET_VENDOR_PENSANDO = no;
NET_VENDOR_QLOGIC = no;
NET_VENDOR_BROCADE = no;
NET_VENDOR_QUALCOMM = no;
NET_VENDOR_RDC = no;
NET_VENDOR_REALTEK = no;
NET_VENDOR_RENESAS = no;
NET_VENDOR_ROCKER = no;
NET_VENDOR_SAMSUNG = no;
NET_VENDOR_SEEQ = no;
NET_VENDOR_SILAN = no;
NET_VENDOR_SIS = no;
NET_VENDOR_SOLARFLARE = no;
NET_VENDOR_SMSC = no;
NET_VENDOR_SOCIONEXT = no;
NET_VENDOR_STMICRO = no;
NET_VENDOR_SUN = no;
NET_VENDOR_SYNOPSYS = no;
NET_VENDOR_TEHUTI = no;
NET_VENDOR_TI = no;
NET_VENDOR_VERTEXCOM = no;
NET_VENDOR_VIA = no;
NET_VENDOR_WANGXUN = no;
NET_VENDOR_WIZNET = no;
NET_VENDOR_XILINX = no;
NET_VENDOR_XIRCOM = no;

# No TV / DVB / radio / SDR hardware.
MEDIA_ANALOG_TV_SUPPORT = lib.mkForce no;
MEDIA_DIGITAL_TV_SUPPORT = lib.mkForce no;
MEDIA_SDR_SUPPORT = no;

# No PCI capture/TV cards.
MEDIA_PCI_SUPPORT = lib.mkForce no;

SND_PCI = no;
SND_DRIVERS = no;
SND_OSSEMUL = lib.mkForce no;

SND_SOC_USB = no;

SND_SOC_ADI_AXI_I2S = no;
SND_SOC_ADI_AXI_SPDIF = no;

SND_SOC_AMD_ACP = no;
SND_SOC_AMD_CZ_DA7219MX98357_MACH = no;
SND_SOC_AMD_CZ_RT5645_MACH = no;
SND_SOC_AMD_ST_ES8336_MACH = no;

SND_SOC_FSL_ASRC = no;
SND_SOC_FSL_SAI = no;
SND_SOC_FSL_MQS = no;
SND_SOC_FSL_AUDMIX = no;
SND_SOC_FSL_SSI = no;
SND_SOC_FSL_SPDIF = no;
SND_SOC_FSL_ESAI = no;
SND_SOC_FSL_MICFIL = no;
SND_SOC_FSL_EASRC = no;
SND_SOC_FSL_XCVR = no;
SND_SOC_FSL_UTILS = no;
SND_SOC_FSL_RPMSG = no;
SND_SOC_IMX_AUDMUX = no;

SND_SOC_INTEL_KEEMBAY = no;
SND_SOC_MTK_BTCVSD = no;
SND_SOC_MESON_T9015 = no;
SND_SOC_SH4_FSI = no;

SND_SOC_RCAR = no;
SND_SOC_MSIOF = no;
SND_SOC_RZ = no;

SND_SOC_ROCKCHIP_I2S = no;
SND_SOC_ROCKCHIP_I2S_TDM = no;
SND_SOC_ROCKCHIP_PDM = no;
SND_SOC_ROCKCHIP_SAI = no;
SND_SOC_ROCKCHIP_SPDIF = no;
SND_SOC_ROCKCHIP_MAX98090 = no;
SND_SOC_ROCKCHIP_RT5645 = no;
SND_SOC_RK3288_HDMI_ANALOG = no;
SND_SOC_RK3399_GRU_SOUND = no;

SND_SOC_SAMSUNG = no;

SND_SOC_SPRD = no;

SND_SOC_STM32_SAI = no;
SND_SOC_STM32_I2S = no;
SND_SOC_STM32_SPDIFRX = no;
SND_SOC_STM32_DFSDM = no;

SND_SOC_TI_EDMA_PCM = no;
SND_SOC_TI_SDMA_PCM = no;
SND_SOC_TI_UDMA_PCM = no;
SND_SOC_DAVINCI_MCASP = no;
SND_SOC_J721E_EVM = no;

SND_SOC_UNIPHIER_AIO = no;
SND_SOC_UNIPHIER_LD11 = no;
SND_SOC_UNIPHIER_PXS2 = no;
SND_SOC_UNIPHIER_EVEA_CODEC = no;

SND_SOC_XILINX_I2S = no;
SND_SOC_XILINX_AUDIO_FORMATTER = no;
SND_SOC_XILINX_SPDIF = no;
SND_SOC_XTFPGA_I2S = no;

SND_SOC_SOF_TOPLEVEL = no;

SND_SOC_AC97_BUS = no;
SND_SOC_ACPI = no;
SND_SOC_APPLE_AOP_AUDIO = no;
SND_SOC_APPLE_MCA = module;
SND_SOC_APPLE_MACAUDIO = module;
SND_SOC_MIKROE_PROTO = no;
SND_SOC_CHV3_I2S = no;
SND_SOC_SDCA_OPTIONAL = no;
SND_SOC_CV1800B_TDM = no;
SND_SOC_CV1800B_ADC_CODEC = no;
SND_SOC_CV1800B_DAC_CODEC = no;
SND_SOC_WM_ADSP = no;
SND_SOC_AC97_CODEC = no;
SND_SOC_ADAU_UTILS = no;
SND_SOC_ADAU1372 = no;
SND_SOC_ADAU1372_I2C = no;
SND_SOC_ADAU1372_SPI = no;
SND_SOC_ADAU1373 = no;
SND_SOC_ADAU1701 = no;
SND_SOC_ADAU17X1 = no;
SND_SOC_ADAU1761 = no;
SND_SOC_ADAU1761_I2C = no;
SND_SOC_ADAU1761_SPI = no;
SND_SOC_ADAU7002 = no;
SND_SOC_ADAU7118 = no;
SND_SOC_ADAU7118_HW = no;
SND_SOC_ADAU7118_I2C = no;
SND_SOC_AK4104 = no;
SND_SOC_AK4118 = no;
SND_SOC_AK4375 = no;
SND_SOC_AK4458 = no;
SND_SOC_AK4554 = no;
SND_SOC_AK4613 = no;
SND_SOC_AK4619 = no;
SND_SOC_AK4642 = no;
SND_SOC_AK5386 = no;
SND_SOC_AK5558 = no;
SND_SOC_ALC5623 = no;
SND_SOC_AUDIO_IIO_AUX = no;
SND_SOC_AW8738 = no;
SND_SOC_AW88395_LIB = no;
SND_SOC_AW88395 = no;
SND_SOC_AW88166 = no;
SND_SOC_AW88261 = no;
SND_SOC_AW88081 = no;
SND_SOC_AW87390 = no;
SND_SOC_AW88399 = no;
SND_SOC_BD28623 = no;
SND_SOC_BT_SCO = no;
SND_SOC_CHV3_CODEC = no;
SND_SOC_CPCAP = no;
SND_SOC_CROS_EC_CODEC = no;
SND_SOC_CS_AMP_LIB = no;
SND_SOC_CS35L32 = no;
SND_SOC_CS35L33 = no;
SND_SOC_CS35L34 = no;
SND_SOC_CS35L35 = no;
SND_SOC_CS35L36 = no;
SND_SOC_CS35L41_LIB = no;
SND_SOC_CS35L41 = no;
SND_SOC_CS35L41_SPI = no;
SND_SOC_CS35L41_I2C = no;
SND_SOC_CS35L45 = no;
SND_SOC_CS35L45_SPI = no;
SND_SOC_CS35L45_I2C = no;
SND_SOC_CS35L56 = no;
SND_SOC_CS35L56_SHARED = no;
SND_SOC_CS35L56_I2C = no;
SND_SOC_CS35L56_SPI = no;
SND_SOC_CS35L56_SDW = no;
SND_SOC_CS40L50 = no;
SND_SOC_CS42L42_CORE = no;
SND_SOC_CS42L42 = no;
SND_SOC_CS42L42_SDW = no;
SND_SOC_CS42L43 = no;
SND_SOC_CS42L43_SDW = no;
SND_SOC_CS42L51 = no;
SND_SOC_CS42L51_I2C = no;
SND_SOC_CS42L52 = no;
SND_SOC_CS42L56 = no;
SND_SOC_CS42L73 = no;
SND_SOC_CS4234 = no;
SND_SOC_CS4265 = no;
SND_SOC_CS4270 = no;
SND_SOC_CS4271 = no;
SND_SOC_CS4271_I2C = no;
SND_SOC_CS4271_SPI = no;
SND_SOC_CS42XX8 = no;
SND_SOC_CS42XX8_I2C = no;
SND_SOC_CS43130 = no;
SND_SOC_CS4341 = no;
SND_SOC_CS4349 = no;
SND_SOC_CS48L32 = no;
SND_SOC_CS53L30 = no;
SND_SOC_CS530X = no;
SND_SOC_CS530X_I2C = no;
SND_SOC_CS530X_SPI = no;
SND_SOC_CX2072X = no;
SND_SOC_DA7213 = no;
SND_SOC_DMIC = no;
SND_SOC_ES7134 = no;
SND_SOC_ES7241 = no;
SND_SOC_ES8311 = no;
SND_SOC_ES8316 = no;
SND_SOC_ES8323 = no;
SND_SOC_ES8326 = no;
SND_SOC_ES8328 = no;
SND_SOC_ES8328_I2C = no;
SND_SOC_ES8328_SPI = no;
SND_SOC_ES8375 = no;
SND_SOC_ES8389 = no;
SND_SOC_FS_AMP_LIB = no;
SND_SOC_FS210X = no;
SND_SOC_GTM601 = no;
SND_SOC_HDA = no;
SND_SOC_ICS43432 = no;
SND_SOC_IDT821034 = no;
SND_SOC_INNO_RK3036 = no;
SND_SOC_MAX98088 = no;
SND_SOC_MAX98090 = no;
SND_SOC_MAX98357A = no;
SND_SOC_MAX98504 = no;
SND_SOC_MAX9867 = no;
SND_SOC_MAX98927 = no;
SND_SOC_MAX98520 = no;
SND_SOC_MAX98363 = no;
SND_SOC_MAX98373 = no;
SND_SOC_MAX98373_I2C = no;
SND_SOC_MAX98373_SDW = no;
SND_SOC_MAX98388 = no;
SND_SOC_MAX98390 = no;
SND_SOC_MAX98396 = no;
SND_SOC_MAX9860 = no;
SND_SOC_MSM8916_WCD_ANALOG = no;
SND_SOC_MSM8916_WCD_DIGITAL = no;
SND_SOC_PCM1681 = no;
SND_SOC_PCM1754 = no;
SND_SOC_PCM1789 = no;
SND_SOC_PCM1789_I2C = no;
SND_SOC_PCM179X = no;
SND_SOC_PCM179X_I2C = no;
SND_SOC_PCM179X_SPI = no;
SND_SOC_PCM186X = no;
SND_SOC_PCM186X_I2C = no;
SND_SOC_PCM186X_SPI = no;
SND_SOC_PCM3060 = no;
SND_SOC_PCM3060_I2C = no;
SND_SOC_PCM3060_SPI = no;
SND_SOC_PCM3168A = no;
SND_SOC_PCM3168A_I2C = no;
SND_SOC_PCM3168A_SPI = no;
SND_SOC_PCM5102A = no;
SND_SOC_PCM512x = no;
SND_SOC_PCM512x_I2C = no;
SND_SOC_PCM512x_SPI = no;
SND_SOC_PCM6240 = no;
SND_SOC_PEB2466 = no;
SND_SOC_PM4125 = no;
SND_SOC_PM4125_SDW = no;
SND_SOC_RK3308 = no;
SND_SOC_RK3328 = no;
SND_SOC_RK817 = no;
SND_SOC_RL6231 = no;
SND_SOC_RT_SDW_COMMON = no;
SND_SOC_RT1017_SDCA_SDW = no;
SND_SOC_RT1308_SDW = no;
SND_SOC_RT1316_SDW = no;
SND_SOC_RT1318_SDW = no;
SND_SOC_RT1320_SDW = no;
SND_SOC_RT5575 = no;
SND_SOC_RT5616 = no;
SND_SOC_RT5631 = no;
SND_SOC_RT5640 = no;
SND_SOC_RT5659 = no;
SND_SOC_RT5682 = no;
SND_SOC_RT5682_SDW = no;
SND_SOC_RT700 = no;
SND_SOC_RT700_SDW = no;
SND_SOC_RT711 = no;
SND_SOC_RT711_SDW = no;
SND_SOC_RT711_SDCA_SDW = no;
SND_SOC_RT712_SDCA_SDW = no;
SND_SOC_RT712_SDCA_DMIC_SDW = no;
SND_SOC_RT721_SDCA_SDW = no;
SND_SOC_RT722_SDCA_SDW = no;
SND_SOC_RT715 = no;
SND_SOC_RT715_SDW = no;
SND_SOC_RT715_SDCA_SDW = no;
SND_SOC_RT9120 = no;
SND_SOC_RT9123 = no;
SND_SOC_RT9123P = no;
SND_SOC_RTQ9124 = no;
SND_SOC_RTQ9128 = no;
SND_SOC_SDW_MOCKUP = no;
SND_SOC_SGTL5000 = no;
SND_SOC_SIGMADSP = no;
SND_SOC_SIGMADSP_I2C = no;
SND_SOC_SIGMADSP_REGMAP = no;
SND_SOC_SIMPLE_AMPLIFIER = no;
SND_SOC_SIMPLE_MUX = no;
SND_SOC_SMA1303 = no;
SND_SOC_SMA1307 = no;
SND_SOC_SPDIF = no;
SND_SOC_SRC4XXX_I2C = no;
SND_SOC_SRC4XXX = no;
SND_SOC_SSM2305 = no;
SND_SOC_SSM2518 = no;
SND_SOC_SSM2602 = no;
SND_SOC_SSM2602_SPI = no;
SND_SOC_SSM2602_I2C = no;
SND_SOC_SSM3515 = no;
SND_SOC_SSM4567 = no;
SND_SOC_STA32X = no;
SND_SOC_STA350 = no;
SND_SOC_STI_SAS = no;
SND_SOC_TAS2552 = no;
SND_SOC_TAS2562 = no;
SND_SOC_TAS2780 = no;
SND_SOC_TAS2781_COMLIB = no;
SND_SOC_TAS2781_COMLIB_I2C = no;
SND_SOC_TAS2781_FMWLIB = no;
SND_SOC_TAS2781_I2C = no;
SND_SOC_TAS5086 = no;
SND_SOC_TAS571X = no;
SND_SOC_TAS5720 = no;
SND_SOC_TAS5805M = no;
SND_SOC_TAS6424 = no;
SND_SOC_TDA7419 = no;
SND_SOC_TFA9879 = no;
SND_SOC_TFA989X = no;
SND_SOC_TLV320ADC3XXX = no;
SND_SOC_TLV320AIC23 = no;
SND_SOC_TLV320AIC23_I2C = no;
SND_SOC_TLV320AIC23_SPI = no;
SND_SOC_TLV320AIC31XX = no;
SND_SOC_TLV320AIC32X4 = no;
SND_SOC_TLV320AIC32X4_I2C = no;
SND_SOC_TLV320AIC32X4_SPI = no;
SND_SOC_TLV320AIC3X = no;
SND_SOC_TLV320AIC3X_I2C = no;
SND_SOC_TLV320AIC3X_SPI = no;
SND_SOC_TLV320ADCX140 = no;
SND_SOC_TS3A227E = no;
SND_SOC_TSCS42XX = no;
SND_SOC_TSCS454 = no;
SND_SOC_UDA1334 = no;
SND_SOC_UDA1342 = no;
SND_SOC_UDA1380 = no;
SND_SOC_WCD_CLASSH = no;
SND_SOC_WCD_COMMON = no;
SND_SOC_WCD9335 = no;
SND_SOC_WCD_MBHC = no;
SND_SOC_WCD934X = no;
SND_SOC_WCD937X = no;
SND_SOC_WCD937X_SDW = no;
SND_SOC_WCD938X = no;
SND_SOC_WCD938X_SDW = no;
SND_SOC_WCD939X = no;
SND_SOC_WCD939X_SDW = no;
SND_SOC_WM8510 = no;
SND_SOC_WM8523 = no;
SND_SOC_WM8524 = no;
SND_SOC_WM8580 = no;
SND_SOC_WM8711 = no;
SND_SOC_WM8728 = no;
SND_SOC_WM8731 = no;
SND_SOC_WM8731_I2C = no;
SND_SOC_WM8731_SPI = no;
SND_SOC_WM8737 = no;
SND_SOC_WM8741 = no;
SND_SOC_WM8750 = no;
SND_SOC_WM8753 = no;
SND_SOC_WM8770 = no;
SND_SOC_WM8776 = no;
SND_SOC_WM8782 = no;
SND_SOC_WM8804 = no;
SND_SOC_WM8804_I2C = no;
SND_SOC_WM8804_SPI = no;
SND_SOC_WM8903 = no;
SND_SOC_WM8904 = no;
SND_SOC_WM8940 = no;
SND_SOC_WM8960 = no;
SND_SOC_WM8961 = no;
SND_SOC_WM8962 = no;
SND_SOC_WM8974 = no;
SND_SOC_WM8978 = no;
SND_SOC_WM8985 = no;
SND_SOC_WSA881X = no;
SND_SOC_WSA883X = no;
SND_SOC_WSA884X = no;
SND_SOC_ZL38060 = no;
SND_SOC_MAX9759 = no;
SND_SOC_MT6351 = no;
SND_SOC_MT6357 = no;
SND_SOC_MT6358 = no;
SND_SOC_MT6660 = no;
SND_SOC_NAU8315 = no;
SND_SOC_NAU8325 = no;
SND_SOC_NAU8540 = no;
SND_SOC_NAU8810 = no;
SND_SOC_NAU8821 = no;
SND_SOC_NAU8822 = no;
SND_SOC_NAU8824 = no;
SND_SOC_NTPFW = no;
SND_SOC_NTP8918 = no;
SND_SOC_NTP8835 = no;
SND_SOC_TPA6130A2 = no;
SND_SOC_LPASS_MACRO_COMMON = no;
SND_SOC_LPASS_WSA_MACRO = no;
SND_SOC_LPASS_VA_MACRO = no;
SND_SOC_LPASS_RX_MACRO = no;
SND_SOC_LPASS_TX_MACRO = no;


            };
            features.rust = true;
          }
        ]
        ++ _kernelPatches;
      } extraArgs
    );

  linux-asahi = callPackage linux-asahi-pkg { };
in
lib.recurseIntoAttrs (linuxPackagesFor linux-asahi)
